### ISSUE TITLE
Support pausing

### ISSUE THREAD

**Issue by tessapower** [tessapower/week-sauce-feb24#17]
Add support so that the player can pause the game using either a button or pressing a specific key on their keyboard.

**Comment by LongcatOwO** [comment]
Support for this can be added using the changes from https://github.com/tessapower/week-sauce-feb24/pull/38.
To do so, hook up the relevant components to the pause/unpause signal of GameStateManager, then assign the "is_paused" property of GameStateManager to activate the signals.

Concerns:
- Will the Pause UIs also be persistent across scenes? If not, care must be taken in disconnecting from the pause/unpause signals once the scene ends to prevent memory leak.
