### ISSUE TITLE
Implement Core Mole Stat System

### ISSUE THREAD

**Issue by LongcatOwO** [tessapower/week-sauce-feb24#25]
HP - health bar for boss, mole died signal.
Time until disappear - seconds before mole disappear forever.
Exp. reward: the amount of experience the player get for killing the mole
Attack Damage: amount of damage per attack inflicted on the player
Attack Speed: number of attacks per second that the mole can execute.
Mole Attack: perform attack on the player according to the given stats
[Optional] Score reward: the score player gets for killing the mole

**Comment by tessapower** [comment]
This data should be added to the mole data resource.

**Comment by LongcatOwO** [comment]
Closing this issue as implemented in https://github.com/tessapower/week-sauce-feb24/pull/64
